POST http://localhost:3001/api/auth/register/ HTTP/1.1
Content-Type: application/json

{
    "username": "Jorge Ocampos",
    "password": "MYCODE1812",
    "notes": [
        {
            "title": "Do homework.",
            "body": "ISHJJDN",
            "Date": "2022-05-06"
        }
    ]
}

###

POST http://localhost:3001/api/auth/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "Jorge Ocampos",
    "password": "MYCODE1812"
}

###
GET http://localhost:3001/api/users/getUser/62a28927c39a04db408fb095 HTTP/1.1

###

GET http://localhost:3001/api/users/getUsers/ HTTP/1.1
###

DELETE http://localhost:3001/api/users/deleteUser/629fd0681508e10cc2eeb80c HTTP/1.1