POST http://localhost:3001/api/auth/register/ HTTP/1.1
Content-Type: application/json

{
    "username": "elPutoFeo",
    "password": "MYCODE1812",
    "notes": [
        {
            "title": "Do homework.",
            "body": "ISHJJDN",
            "Date": "2022-05-06"
        }
    ]
}

###

POST http://localhost:3001/api/auth/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "elPutoFeo",
    "password": "MYCODE1812"
}

###
GET http://localhost:3001/api/users/getUser/629d4f3fa2355ad80f7719c7 HTTP/1.1

###

GET http://localhost:3001/api/users/getUsers/ HTTP/1.1
###

DELETE http://localhost:3001/api/users/deleteUser/629d6d4fda0444dcf5525358 HTTP/1.1